name: Java SNAPSHOT Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'

jobs:
  release-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build and Publish SNAPSHOT
        run: ./mvnw deploy -B -V -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
